version: 2.1
jobs:
  build:
    environment:
      GO111MODULE: "on"
      CONSUL_VERSION: 1.10.7
      VAULT_VERSION: 1.8.8
      NOMAD_VERSION: "1.3.0-beta.1"
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - ct-modcache-v1-{{ checksum "go.mod" }}
      - run: |
          curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
          unzip consul.zip
          sudo cp consul /usr/local/bin/
      - run: |
          curl -sLo vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
          unzip vault.zip
          sudo cp vault /usr/local/bin/
      - run: |
          curl -sLo nomad.zip https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip
          unzip nomad.zip
          sudo cp nomad /usr/local/bin/
      - run: |
          make test
      - save_cache:
          key: ct-modcache-v1-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
